baseURL = 'https://ghugo.synbe.com/'
locale = 'en-us'
title = 'chugo'
theme = 'ananke'

[params]
  author = 'axun'
  description = '记录技术、思考与沿途的风景'
  show_reading_time = true

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '文章'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 3
